### ISSUE TITLE
网站图标全都挂了，扶墙后也一样

### ISSUE THREAD

**Issue by he-sb** [sleepwood/CF-Worker-Dir#6]
如图：

![图片](https://user-images.githubusercontent.com/26474615/82530099-1a1ced80-9b6f-11ea-8b77-95e6240830bc.png)

**Comment by MacroHarry** [comment]
PR created.
已修复，等待合并

**Comment by he-sb** [comment]
> 
> 
> Edit: No need to fix， it's "icon.occ.hk"'s certs problem. 不需要修复，用来获取favicon的网站的证书有问题。如果不介意的话可以把获取favicon的函数改成http的。
> PR created.
> 已修复，等待合并

ok，谢谢老哥。

**Comment by fuzz-cqu** [comment]
you can use
https://www.google.cn/s2/favicons?domain_url=

**Comment by MacroHarry** [comment]
It works but google recode the fav icon and restrict the size to 16*16 which reduced the quality most of the time. In cases where full-TLS is required this seem to be a good workaround.

**Comment by MacroHarry** [comment]
> you can use
> https://www.google.cn/s2/favicons?domain_url=

It works but google recode the fav icon and restrict the size to 16*16 which reduced the quality most of the time. In cases where full-TLS is required this seem to be a good workaround.
